# Generated by Django 3.0.4 on 2020-03-25 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_booksnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Books')),
            ],
        ),
    ]
